import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import { useMemo } from 'react';
import Main from '../Layout/Main';
import { Box, Button, Grid, IconButton, TextField, Typography } from '@mui/material';
import SendIcon from '@mui/icons-material/Send';
import ShoppingCartIcon from '@mui/icons-material/ShoppingCart';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main className={styles.main}>
        <Box marginBottom={10}>
          <Typography variant='h1'>
             Welcome, <Link href='/'>Face2Face</Link>
          </Typography>
          <Typography variant='subtitle1'>
            F2F is a <b>face-to-face</b> trading platform for second-hand goods
          </Typography>
        </Box>

        <Grid container>
          <Grid xs={10} md={8} lg={6}>
            <TextField id="search-box" label="What's your interested?" variant='outlined' fullWidth placeholder='I feel lucky!' />
          </Grid>
        </Grid>
      </Main>
      <main>

      </main>
    </div>
  )
}

export async function getServerSideProps({ req, res }) {

  console.log(req, res)

  return {
    props: {}, // Will be passed to the page component as props
  }
}