import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import { useCallback, useMemo, useState } from 'react';
import Main from '../Layout/Main';
import { Box, Button, Grid, IconButton, TextField, Typography, Item, Container, List, ListItem } from '@mui/material';
import SendIcon from '@mui/icons-material/Send';
import ShoppingCartIcon from '@mui/icons-material/ShoppingCart';
import { useLazyQuery } from '@apollo/client';
import { GET_PRODUCTION_IDS_BY_NAME } from '../graphql/apis';
import ProductItem from '../components/ProductItem';
import { height } from '@mui/system';

export default function Home() {

  const [products, setProducts] = useState([]);

  // search
  const [doSearchProduct, { loading }] = useLazyQuery(GET_PRODUCTION_IDS_BY_NAME, {
    fetchPolicy: 'no-cache'
  });

  const onSearchInputChange = useCallback(async (event) => {
    event.preventDefault();
    const keyword = event.target.value;

    if (keyword === '')
      return;

    const { error, data } = await doSearchProduct({
      variables: {
        name: keyword,
        activate: true
      },
    });

    if (!error) {
      setProducts(data.productions);
    }

  }, [doSearchProduct]);

  const loginUser = typeof window === 'undefined' ? '' : JSON.parse(localStorage.getItem('loginUser'));

  return (
    <>
      <Head>
        <title>Welcome {loginUser?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main className={styles.main}>
        <Box marginBottom={10}>
          <Typography variant='h1'>
            Welcome <Link href='/'>Face2Face</Link>
          </Typography>
          <Typography variant='subtitle1'>
            F2F is a <b>face-to-face</b> trading platform for second-hand goods
          </Typography>
          <div style={{ height: '4vh' }}></div>
          <TextField id="search-box" label="What's your interested?" variant='outlined' fullWidth placeholder='I feel lucky!' onChange={onSearchInputChange} />
        </Box>
        <Grid container spacing={10}>
          {
            products.map(product => <Grid item md={4} marginBottom={2} key={product._id}><ProductItem key={product._id} pid={product._id} /></Grid>)
          }
        </Grid>
      </Main>
    </>
  )
}